[package]
name = "https-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pki-types = "1.0"
rustls-pemfile = "2.0"
openssl = "0.10"
clap = { version = "4.5", features = ["derive"] }
