[package]
name = "https-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
hyper = { version = "1.0", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
rustls = "0.22"
tokio-rustls = "0.24"
rustls-pemfile = "2.1"
rcgen = "0.12"
